language: python            # this works for Linux but is an error on macOS or Windows
jobs:
  include:
    - name: "Python 3.7.0 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

install: pip3 install --upgrade pip  # all three OSes agree about 'pip3'
# 'python' points to Python 2.7 on macOS but points to Python 3.8 on Linux and Windows
# 'python3' is a 'command not found' error on Windows but 'py' works on Windows only
script: python3 my_app.py || python my_app.py

# before_install:
#   - sudo apt-get update
#   # We do this conditionally because it saves us some downloading if the
#   # version is the same.
#   - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
#       wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
#     else
#       wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
#     fi
#   - bash miniconda.sh -b -p $HOME/miniconda
#   - source "$HOME/miniconda/etc/profile.d/conda.sh"
#   - hash -r
#   - conda config --set always_yes yes --set changeps1 no
#   - conda update -q conda
#   # Useful for debugging any issues with conda
#   - conda info -a

#   # Replace dep1 dep2 ... with your dependencies
#   - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
#   - conda activate test-environment
#   #- python setup.py install
install:
  - conda install -c rdkit rdkit
script:
  - python setup.py install
  - python ./tests/ScoDruglikeness.py
  - python ./tests/ScoFH.py