name: scopy-2
channels:
  - kotori_y
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.2
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - boost=1.74.0
  - boost-cpp=1.74.0
  - brotli=1.0.7
  - bzip2=1.0.8
  - ca-certificates=2021.10.8
  - cairo=1.16.0
  - certifi=2021.10.8
  - cycler=0.11.0
  - decorator=5.1.1
  - expat=2.4.1
  - fontconfig=2.13.94
  - fonttools=4.25.0
  - freetype=2.11.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - greenlet=1.1.2
  - icu=68.2
  - ipython=7.29.0
  - jedi=0.18.1
  - jpeg=9d
  - kiwisolver=1.3.1
  - lcms2=2.12
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=12.0.0
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.1.0
  - libglib=2.68.4
  - libiconv=1.16
  - liblapack=3.9.0
  - libpng=1.6.37
  - libtiff=4.2.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libxml2=2.9.12
  - llvm-openmp=12.0.0
  - lz4-c=1.9.3
  - matplotlib=3.5.0
  - matplotlib-base=3.5.0
  - matplotlib-inline=0.1.3
  - munkres=1.1.4
  - ncurses=6.3
  - numpy=1.21.1
  - olefile=0.46
  - openssl=1.1.1l
  - packaging=21.3
  - pandas=1.3.4
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.3.1
  - pip=21.2.4
  - pixman=0.40.0
  - prompt-toolkit=3.0.26
  - ptyprocess=0.7.0
  - pycairo=1.20.1
  - pygments=2.11.2
  - pyparsing=3.0.4
  - python=3.9.7
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytz=2021.3
  - rdkit=2021.09.2
  - readline=8.1.2
  - reportlab=3.5.68
  - scopy=1.2.5
  - setuptools=58.0.4
  - six=1.16.0
  - sqlalchemy=1.4.26
  - sqlite=3.37.0
  - tk=8.6.11
  - tornado=6.1
  - traitlets=5.1.1
  - tzdata=2021e
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
