package:
  name: scopy
  version: 1.2.0

source:
  git_url: https://github.com/kotori-y/Scopy.git
  git_rev: master
  git_depth: 1 # (Defaults to -1/not shallow)

build:
  noarch: python
  number: 1
  script: python setup.py install

requirements:
  host:
    - python
    - pip
  run:
    - python

about:
  home: https://github.com/kotori-y/Scopy
  license: MIT
  summary: 'A compounds filter for HTS and VS'
  description: |
    Scopy(Screening COmpounds in PYthon), based on RDKit, 
    is an integrated negative design python library designed for 
    screening out undesiable compounds in the early drug discovery.
  dev_url: https://github.com/kotori-y/Scopy
  doc_url: https://scopy.readthedocs.io/en/latest/
  doc_source_url: https://github.com/kotori-y/Scopy